---
jobs:
- name: alpine-bash-curl
  public: true
  serial: true
  plan:
  - get: builds-repo
  - task: curl
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: flygare/alpine-bash-curl}
      inputs:
      - name: builds-repo
      run:
        path: builds-repo/tasks/build.sh
        args: [
        ((alpine-bash-curl-repo)),
        ((alpine-bash-curl-token))
        ]

resources:
- name: builds-repo
  type: git
  source:
    uri: https://www.github.com/rjain15/docker-builds.git
