---
jobs:
- name: docker-build
  public: true
  serial: true
  plan:
  - get: resource-docker-build-repo
  - task: curl
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: byrnedo/alpine-curl}
      inputs:
      - name: resource-docker-build-repo
      run:
        path: tasks/build.sh
        args: [
        "((REPO))",
        "((TOKEN))"
        ]

resources:
- name: resource-docker-build-repo
  type: git
  source:
    uri: https://www.github.com/rjain15/docker-builds.git
